locale: "en-US"
title: "Zein Pishbin"
description: "Academic webpage"
url: "https://PishbinZ.github.io"
baseurl: ""
repository: "PishbinZ/PishbinZ.github.io"

# If your theme expects this setting, keep it
site_theme: "default"

author:
  name: "Zein Pishbin"
  avatar: "profile.png"
  location: "Paris, France"
  employer: "Universit√© Paris Dauphine-PSL"
  email: "zeinab.s.pishbin@gmail.com"
  googlescholar: "https://scholar.google.com/citations?user=qSy13-cAAAAJ"

include:
  - _pages
  - files

markdown: kramdown
highlighter: rouge

collections:
  publications:
    output: true
    permalink: /publications/:path/
  teaching:
    output: true
    permalink: /teaching/:path/

defaults:
  - scope:
      path: ""
      type: pages
    values:
      layout: single

  - scope:
      path: ""
      type: publications
    values:
      layout: single

  - scope:
      path: ""
      type: teaching
    values:
      layout: single

plugins:
  - jekyll-sitemap
