# Basic
title: "Zein Pishbin"
description: "Academic webpage"
locale: "en-US"

url: "https://PishbinZ.github.io"
baseurl: ""          # keep empty for username.github.io sites

# Use a stable GitHub Pages supported theme
theme: minima

repository: "PishbinZ/PishbinZ.github.io"

author:
  name: "Zein Pishbin"
  email: "zeinab.s.pishbin@gmail.com"
  location: "Paris, France"
  employer: "Universit√© Paris Dauphine-PSL"
  googlescholar: "https://scholar.google.com/citations?user=qSy13-cAAAAJ"
  avatar: "files/profile.png"

include:
  - _pages
  - files
  - assets

markdown: kramdown

defaults:
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: page

plugins:
  - jekyll-sitemap

header_pages:
  - _pages/publications.md
  - _pages/teaching.md
  - _pages/cv.md
